# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Labra.ui pääohjelma.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QLineEdit, QMainWindow,
    QMenuBar, QPushButton, QSizePolicy, QSpinBox,
    QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(550, 361)
        font = QFont()
        font.setPointSize(8)
        MainWindow.setFont(font)
        self.actionLopeta = QAction(MainWindow)
        self.actionLopeta.setObjectName(u"actionLopeta")
        self.actionViivakoodi = QAction(MainWindow)
        self.actionViivakoodi.setObjectName(u"actionViivakoodi")
        self.actionNimilappu = QAction(MainWindow)
        self.actionNimilappu.setObjectName(u"actionNimilappu")
        self.actionTallenna_2 = QAction(MainWindow)
        self.actionTallenna_2.setObjectName(u"actionTallenna_2")
        self.actionTulosta_2 = QAction(MainWindow)
        self.actionTulosta_2.setObjectName(u"actionTulosta_2")
        self.actionKopio = QAction(MainWindow)
        self.actionKopio.setObjectName(u"actionKopio")
        self.actionLiit = QAction(MainWindow)
        self.actionLiit.setObjectName(u"actionLiit")
        self.actionLeikkaa = QAction(MainWindow)
        self.actionLeikkaa.setObjectName(u"actionLeikkaa")
        self.actionArvot = QAction(MainWindow)
        self.actionArvot.setObjectName(u"actionArvot")
        self.actionKaavat = QAction(MainWindow)
        self.actionKaavat.setObjectName(u"actionKaavat")
        self.actionMuotoilu = QAction(MainWindow)
        self.actionMuotoilu.setObjectName(u"actionMuotoilu")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.henkiltunnus_2 = QLineEdit(self.centralwidget)
        self.henkiltunnus_2.setObjectName(u"henkiltunnus_2")
        self.henkiltunnus_2.setGeometry(QRect(20, 40, 231, 41))
        font1 = QFont()
        font1.setFamilies([u"Arial Black"])
        font1.setPointSize(20)
        self.henkiltunnus_2.setFont(font1)
        self.henkiltunnus_2.setMouseTracking(True)
        self.henkiltunnus_2.setToolTipDuration(3000)
        self.henkiltunnus_2.setLocale(QLocale(QLocale.Finnish, QLocale.Finland))
        self.henkiltunnus_2.setCursorMoveStyle(Qt.VisualMoveStyle)
        self.henkiltunnus_2.setClearButtonEnabled(True)
        self.henkiltunnus = QLabel(self.centralwidget)
        self.henkiltunnus.setObjectName(u"henkiltunnus")
        self.henkiltunnus.setGeometry(QRect(20, 20, 71, 16))
        self.firstNameLineEdit = QLineEdit(self.centralwidget)
        self.firstNameLineEdit.setObjectName(u"firstNameLineEdit")
        self.firstNameLineEdit.setGeometry(QRect(20, 140, 231, 41))
        self.firstNameLineEdit.setFont(font1)
        self.firstNameLineEdit.setMouseTracking(True)
        self.firstNameLineEdit.setLocale(QLocale(QLocale.Finnish, QLocale.Finland))
        self.ssnLastNameEdit = QLineEdit(self.centralwidget)
        self.ssnLastNameEdit.setObjectName(u"ssnLastNameEdit")
        self.ssnLastNameEdit.setGeometry(QRect(270, 140, 231, 41))
        self.ssnLastNameEdit.setFont(font1)
        self.ssnLastNameEdit.setMouseTracking(True)
        self.ssnLastNameEdit.setLocale(QLocale(QLocale.Finnish, QLocale.Finland))
        self.firstNameEditLabel = QLabel(self.centralwidget)
        self.firstNameEditLabel.setObjectName(u"firstNameEditLabel")
        self.firstNameEditLabel.setGeometry(QRect(20, 120, 41, 16))
        self.lastNameEDitiom = QLabel(self.centralwidget)
        self.lastNameEDitiom.setObjectName(u"lastNameEDitiom")
        self.lastNameEDitiom.setGeometry(QRect(270, 120, 71, 20))
        self.barcodeLabel = QLabel(self.centralwidget)
        self.barcodeLabel.setObjectName(u"barcodeLabel")
        self.barcodeLabel.setGeometry(QRect(20, 200, 181, 71))
        font2 = QFont()
        font2.setFamilies([u"Libre Barcode 128 Text"])
        font2.setPointSize(36)
        self.barcodeLabel.setFont(font2)
        self.Tulosta = QPushButton(self.centralwidget)
        self.Tulosta.setObjectName(u"Tulosta")
        self.Tulosta.setGeometry(QRect(370, 210, 131, 41))
        font3 = QFont()
        font3.setPointSize(18)
        self.Tulosta.setFont(font3)
        self.Tulosta.setStyleSheet(u"")
        self.maara = QSpinBox(self.centralwidget)
        self.maara.setObjectName(u"maara")
        self.maara.setGeometry(QRect(270, 210, 91, 41))
        font4 = QFont()
        font4.setPointSize(24)
        self.maara.setFont(font4)
        self.maara.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.maara.setMaximum(99)
        self.amountStickerLabel = QLabel(self.centralwidget)
        self.amountStickerLabel.setObjectName(u"amountStickerLabel")
        self.amountStickerLabel.setGeometry(QRect(270, 190, 81, 16))
        self.amountStickerLabel_2 = QLabel(self.centralwidget)
        self.amountStickerLabel_2.setObjectName(u"amountStickerLabel_2")
        self.amountStickerLabel_2.setGeometry(QRect(20, 190, 61, 16))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 550, 19))
        MainWindow.setMenuBar(self.menubar)
        QWidget.setTabOrder(self.henkiltunnus_2, self.firstNameLineEdit)
        QWidget.setTabOrder(self.firstNameLineEdit, self.ssnLastNameEdit)
        QWidget.setTabOrder(self.ssnLastNameEdit, self.maara)
        QWidget.setTabOrder(self.maara, self.Tulosta)

        self.retranslateUi(MainWindow)
        self.henkiltunnus_2.textChanged.connect(self.barcodeLabel.setText)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionLopeta.setText(QCoreApplication.translate("MainWindow", u"Lopeta", None))
        self.actionViivakoodi.setText(QCoreApplication.translate("MainWindow", u"Viivakoodi", None))
        self.actionNimilappu.setText(QCoreApplication.translate("MainWindow", u"Nimilappu", None))
        self.actionTallenna_2.setText(QCoreApplication.translate("MainWindow", u"Tallenna...", None))
#if QT_CONFIG(shortcut)
        self.actionTallenna_2.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionTulosta_2.setText(QCoreApplication.translate("MainWindow", u"Tulosta", None))
#if QT_CONFIG(tooltip)
        self.actionTulosta_2.setToolTip(QCoreApplication.translate("MainWindow", u"Tulosta", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionTulosta_2.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+B", None))
#endif // QT_CONFIG(shortcut)
        self.actionKopio.setText(QCoreApplication.translate("MainWindow", u"Kopio", None))
#if QT_CONFIG(shortcut)
        self.actionKopio.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+C", None))
#endif // QT_CONFIG(shortcut)
        self.actionLiit.setText(QCoreApplication.translate("MainWindow", u"Liit\u00e4", None))
#if QT_CONFIG(shortcut)
        self.actionLiit.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+V", None))
#endif // QT_CONFIG(shortcut)
        self.actionLeikkaa.setText(QCoreApplication.translate("MainWindow", u"Leikkaa", None))
#if QT_CONFIG(shortcut)
        self.actionLeikkaa.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+X", None))
#endif // QT_CONFIG(shortcut)
        self.actionArvot.setText(QCoreApplication.translate("MainWindow", u"Arvot", None))
        self.actionKaavat.setText(QCoreApplication.translate("MainWindow", u"Kaavat", None))
        self.actionMuotoilu.setText(QCoreApplication.translate("MainWindow", u"Muotoilu", None))
#if QT_CONFIG(tooltip)
        self.henkiltunnus_2.setToolTip(QCoreApplication.translate("MainWindow", u"Suomalainen henkil\u00f6tunnus", None))
#endif // QT_CONFIG(tooltip)
        self.henkiltunnus_2.setPlaceholderText(QCoreApplication.translate("MainWindow", u"311259-123X", None))
        self.henkiltunnus.setText(QCoreApplication.translate("MainWindow", u"Henkil\u00f6tunnus", None))
        self.firstNameEditLabel.setText(QCoreApplication.translate("MainWindow", u"Etunimi", None))
        self.lastNameEDitiom.setText(QCoreApplication.translate("MainWindow", u"Sukunimi", None))
        self.barcodeLabel.setText(QCoreApplication.translate("MainWindow", u"ppkkvv-nnnv", None))
        self.Tulosta.setText(QCoreApplication.translate("MainWindow", u"Tulosta", None))
        self.amountStickerLabel.setText(QCoreApplication.translate("MainWindow", u"Etikettien m\u00e4\u00e4r\u00e4", None))
        self.amountStickerLabel_2.setText(QCoreApplication.translate("MainWindow", u"Mallietiketti", None))
    # retranslateUi

